version: '3'
services:
  entries-frontend-app:
    container_name: entries-frontend-app
    build: .
    ports:
      - "3001:3001"
    networks:
      - entries-backend-app_entries-app-network

networks:
  entries-backend-app_entries-app-network:
    name: "entries-backend-app_entries-app-network"
    external: true
